### ISSUE TITLE
Cannot gradle sync project

### ISSUE THREAD

**Issue by kada49** [EssentialGG/essential-gradle-toolkit#10]
![Screenshot 2023-01-12 014009](https://user-images.githubusercontent.com/45010661/211948686-bda495ca-530d-4827-853b-93b90568d338.png)
When reloading the project this happens

**Comment by DJtheRedstoner** [comment]
Resolved by selecting JDK 17 as Project SDK and setting `Settings -> Build, Executation and Deployment -> Build Tools -> Gradle -> Gradle JDK` to Project SDK in IntelliJ.

**Comment by kada49** [comment]
was about to close the issue, thank you! (the "fix" makes me look stoopid)
