### ISSUE TITLE
Be cursed, support snapshots

### ISSUE THREAD

**Issue by thecatcore** [EssentialGG/essential-gradle-toolkit#6]

**Comment by DJtheRedstoner** [comment]
EGT allows you to override MC versions/mappings using gradle properties. Here's [an example](https://github.com/EssentialGG/UniversalCraft/pull/43/commits/48905ee43d94f506ce0cde945f488493daf7f004#diff-d6cd719978e673bbe4e703040616a52818ab722c4f8cc169825cdb331945b3d3). If you setup for a version not contained in the built in defaults, it will throw convenient errors describing what properties to set. If you need more support, using #dev-chat in [our discord](https://discord.gg/essential) is preferred.
